# Generated by Django 5.1.5 on 2025-01-18 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='cal_events',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='app.calendarevent'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='prof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendars', to='app.Staff'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Avatar Image', null=True, upload_to='avatar'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('assistant', "Doctor's Assistant"), ('patient', 'Patient')], default='patient', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='social_sec_number',
            field=models.IntegerField(help_text='Social Security Number', unique=True),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='The subject of the message.', max_length=255)),
                ('content', models.TextField(help_text='The body of the message.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The time the message was sent.')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the recipient has read the message.')),
                ('recipient', models.ForeignKey(help_text='The user receiving the message.', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='The user sending the message.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-timestamp'],
            },
        ),
    ]
