# Generated by Django 5.1.5 on 2025-01-18 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_calendar_cal_events_alter_calendar_prof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
    ]
