# Generated by Django 5.1.5 on 2025-01-18 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_message_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('assistant', "Doctor's Assistant"), ('patient', 'Patient')], default='patient', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(help_text='The user sending the message.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='app.patient'),
        ),
    ]
