# Generated by Django 5.1.5 on 2025-01-22 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_customuser_role_alter_message_sender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Staff', 'verbose_name_plural': 'Staff Members'},
        ),
        migrations.RemoveField(
            model_name='staff',
            name='title',
        ),
        migrations.AddField(
            model_name='staff',
            name='license',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prof_in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.staff'),
        ),
    ]
